services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
