name: Frontend Deployment

on:
  push:
    branches:
      - prestaging

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Hook
        run: |
          curl "https://api.render.com/deploy/srv-cv68biqn91rc73bcuv0g?key=Ww42GaSIYUA"
