name: Frontend Deployment

on:
  push:
    branches:
      - prestaging

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Hook
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK }}
